[server]
host = "127.0.0.1" 
port = 8080 
sizeLimit = 125 # MB
enableH2C = false
debug = false

[pages]
enabled = false
staticDir = "/usr/local/ghproxy/pages" 

[log]
logFilePath = "/usr/local/ghproxy/log/ghproxy.log" 
maxLogSize = 5 # MB
level = "info" # dump, debug, info, warn, error, none

[cors]
enabled = true

[auth]
authMethod = "parameters" # "header" or "parameters"
authToken = "token"
enabled = false
passThrough = false

[blacklist]
blacklistFile = "/usr/local/ghproxy/config/blacklist.json"
enabled = false

[whitelist]
enabled = false
whitelistFile = "/usr/local/ghproxy/config/whitelist.json"

[rateLimit]
enabled = false
rateMethod = "total" # "ip" or "total"
ratePerMinute = 180
burst = 5

[outbound]
enabled = false
url = "socks5://127.0.0.1:1080" # "http://127.0.0.1:7890"
