name: Build NoCache Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'VERSION'

jobs:  
  docker:
    runs-on: ubuntu-latest 
    env:
      IMAGE_NAME: wjqserver/ghproxy  # 定义镜像名称变量
      DOCKERFILE: docker/dockerfile/nocache/Dockerfile  # 定义 Dockerfile 路径变量

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load VERSION
        run: |
          if [ -f VERSION ]; then
            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          else
            echo "VERSION file not found!" && exit 1
          fi
      - name: Wait for Compile
        run: sleep 300s

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建镜像
        uses: docker/build-push-action@v6
        with:
          file: ./${{ env.DOCKERFILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: | 
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-nocache
            ${{ env.IMAGE_NAME }}:nocache
